spring:
  application:
    name: SpringCoursera

  jpa:
    hibernate:
      ddl-auto: none


  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB

aws:
  s3:
    bucketName: ${S3_BUCKET_NAME}
    accessKey: ${S3_ACCESS_KEY}
    secretKey: ${S3_SECRET_KEY}

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration-time: ${JWT_EXPIRATION_TIME}

paypal:
  clientId: ${PAYPAL_CLIENT_ID}
  clientSecret: ${PAYPAL_CLIENT_SECRET}