spring:
  application:
    name: SpringCoursera
  datasource:
    url: jdbc:mysql://localhost:3307/coursera
    username: root
    password: 123

  jpa:
    hibernate:
      ddl-auto: none

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/coursera-realm

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  web:
    resources:
      static-locations: /files/

  data:
    mongodb:
      authentication-database: admin
      host: localhost
      port: 27017
      database: mongo-coursera

logging:
  level:
    org.springframework.security: DEBUG

#      uri: mongodb://root:password@localhost:27017/coursera?authSource=admin
file:
  upload-dir: ./files

#amazonProperties:
#  endpointUrl: https://s3.us-east-2.amazonaws.com
#  accessKey: AKIAVVZPCC77BALE3CUQ
#  secretKey: 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
#  bucketName: vuongnhattin-bucker

aws:
  s3:
    bucketName: vuongnhattin-bucket
    accessKey: AKIAVVZPCC77OTYP3ZSU
    secretKey: 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
#    accessKey: AKIAVVZPCC77BALE3CUQ
#    secretKey: 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