spring:
  application:
    name: SpringCoursera

  config:
    import: "optional:env"

  jpa:
    hibernate:
      ddl-auto: none


  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB

aws:
  s3:
    bucketName: vuongnhattin-bucket
    accessKey: AKIAVVZPCC77OTYP3ZSU
    secretKey: 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
#    bucketName: ${S3_BUCKET_NAME}
#    accessKey: ${S3_ACCESS_KEY}
#    secretKey: ${S3_SECRET_KEY}

security:
  jwt:
    secret-key: ZCQl6X6kQnI8PElWxA547cvvvzZSeRhQAzDe7ZYpOI0=
    expiration-time: 3600000
#    secret-key: ${JWT_SECRET_KEY}
#    expiration-time: ${JWT_EXPIRATION_TIME}

paypal:
  clientId: AWYyAJYgpQ09CbsdsYV8qR4yl4BdPZevd_4xmgQWt1BXTztV3XhuU6gCXIZLuQT7JGrWX40DtKEejvWN
  clientSecret: EKUUJyaRGdqrcWr5--7WQ5KKFXdpjDfFhZrrLK5nOcM8wPTo3IF3BAn2_4meR-rhI7MeLZG55j7WP9Vy
#  clientId: ${PAYPAL_CLIENT_ID}
#  clientSecret: ${PAYPAL_CLIENT_SECRET}