spring:
  datasource:
    url: jdbc:mysql://localhost:3307/coursera
    username: root
    password: 123

  data:
    mongodb:
      authentication-database: admin
      host: localhost
      port: 27017
      database: mongo-coursera