spring:
  application:
    name: SpringCoursera
  datasource:
    url: jdbc:mysql://localhost:3307/coursera
    username: root
    password: 123

  jpa:
    hibernate:
      ddl-auto: none

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/coursera-realm

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  web:
    resources:
      static-locations: /files/

  data:
    mongodb:
      authentication-database: admin
      host: localhost
      port: 27017
      database: mongo-coursera
#      uri: mongodb://root:password@localhost:27017/coursera?authSource=admin
file:
  upload-dir: ./files
