spring:
  application:
    name: SpringCoursera
  datasource:
    url: jdbc:mysql://localhost:3307/coursera
    username: root
    password: 123

  jpa:
    hibernate:
      ddl-auto: none

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/coursera-realm

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  web:
    resources:
      static-locations: /files/

  data:
    mongodb:
      authentication-database: admin
      host: localhost
      port: 27017
      database: mongo-coursera

file:
  upload-dir: ./files


aws:
  s3:
    bucketName: vuongnhattin-bucket
    accessKey: AKIAVVZPCC77OTYP3ZSU
    secretKey: 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
#    accessKey: AKIAVVZPCC77BALE3CUQ
#    secretKey: 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

keycloak:
  realm: coursera-realm
  auth-server-url: http://localhost:8080/auth
  ssl-required: none
  resource: demo-app
  use-resource-role-mappings: true
  bearer-only: true
  cors: true
  principal-attribute: preferred_username

#springdoc:
#  swagger-ui:
#    oauth:
#      client-id: angular-client
#      client-secret: